title:            David McCormack's blog
description:      Random thoughts on some DevOps fun I have had.
# Your site's domain goes here. Leave localhost server or blank when working locally.
# url:              http://localhost:4000
url:              http://localhost/dmc7337
# url:              http://dmc7337.github.io
disqus_shortname: dmc7337

# Owner/author information
owner:
  name:           David McCormack
  avatar:         bio-photo.jpg
  bio:            "My name is David McCormack and my username on most of my online sites is dmc7337.
                   No good reason for this choice except that it was available on most sites.
                   I have worked as an IT consultant in finacial services for a number of years and
                   am currently concentrating on DevOps in large enterprises."
  email:          dmc@7337.io
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: dmc7337
  facebook: dmc7337@gmail.com
  github: dmc7337
  stackoverflow: dmc7337
  linkedin: dmc7337
  instagram:
  pinterest: dmc7337
  # For Google Authorship https://plus.google.com/authorship
  google_plus: dmc7337

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Posts
    url: /posts/
  - title: Theme Setup
    url: /theme-setup/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Australia/Melbourne
future:      true
# pygments:    true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
